"""plate table

Revision ID: 2f6af140bdbc
Revises: 
Create Date: 2020-12-14 15:41:17.946138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6af140bdbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_plate'), 'plate', ['plate'], unique=True)
    op.create_index(op.f('ix_plate_timestamp'), 'plate', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_timestamp'), table_name='plate')
    op.drop_index(op.f('ix_plate_plate'), table_name='plate')
    op.drop_table('plate')
    # ### end Alembic commands ###
